# fly.toml file generated for hidden-bush-2663 on 2023-09-06T20:24:38-07:00

app = "hidden-bush-2663"

kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
  

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  builder = "heroku/buildpacks:20"
  [build.args]
    NODE_VERSION = "16.20.2"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  
  [services.http_checks]
    interval = 10000
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
